### ISSUE TITLE
Importing library?

### ISSUE THREAD

**Issue by rickybloomfield** [rubensousa/BottomSheetBuilder#1]
Hi - I've followed the instructions here exactly and the project is not compiling for me - gradle is building without errors (meaning it's pulling in the library), but the project isn't finding it at all:

<img width="726" alt="screen shot 2016-03-23 at 2 57 08 pm" src="https://cloud.githubusercontent.com/assets/868473/13997268/aa3ad27c-f107-11e5-90da-5be6c0469a24.png">

Every other repo I use works fine. Thoughts?

**Comment by rubensousa** [comment]
Hi, can you please share your app's build.gradle? 
It should look like this:

```
apply plugin: 'com.android.application'

repositories{
    maven { url "https://jitpack.io" }
}

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.github.rubensousa.bottomsheetbuilder.sample"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.2.0'
    compile 'com.android.support:design:23.2.0'
    compile 'com.github.rubensousa:BottomSheetBuilder:0.3'
}
```

**Comment by rickybloomfield** [comment]
Thanks. I ended up cleaning and rebuilding and that fixed it. Silly Android Studio! Sorry for the false alarm!

**Comment by rubensousa** [comment]
I'm glad you fixed it :)
