### ISSUE TITLE
Why i open the whole panel is white? The item is not loaded

### ISSUE THREAD

**Issue by RealFeeling** [rubensousa/BottomSheetBuilder#15]
private void show() {

        if (mBottomSheetDialog != null) {
            mBottomSheetDialog.dismiss();
        }

        mBottomSheetDialog = new BottomSheetBuilder(this, R.style.BottomSheetBuilder_DialogStyle)
                .setMode(BottomSheetBuilder.MODE_GRID)
                .setMenu(R.menu.menu_share)
                .expandOnStart(true)
                .setItemClickListener(new BottomSheetItemClickListener() {
                    @Override
                    public void onBottomSheetItemClick(MenuItem item) {
                        CUtils.Toast(item.getTitle() + "");

                    }
                })
                .createDialog();

        mBottomSheetDialog.show();

    }

**Comment by rubensousa** [comment]
I didn't understand the question. Can you explain it again? You could also provide a screenshot that demos the issue, if there's any.

**Comment by rubensousa** [comment]
Closing due to no response.
