### ISSUE TITLE
Menu Item Visibility

### ISSUE THREAD

**Issue by Bob-Snyder** [rubensousa/BottomSheetBuilder#2]
A desirable enhancement would be for `BottomSheetBuilder` to check the visibility status of a menu item before adding it to the list of `BottomSheetItems` in method `createMenuItems()`.  In my use case, I have a single menu resource XML file that I configure after inflation by calling `MenuItem.setVisible()` to make items visible or not depending on the context.  When I pass the menu to `BottomSheetBuilder.setMenu(Menu)`, the visibility status of the menu items is ignored.

**Comment by rubensousa** [comment]
Added in [1.1](https://github.com/rubensousa/BottomSheetBuilder/releases/tag/1.1).
Thanks for the suggestion!

**Comment by Bob-Snyder** [comment]
Version 1.1 works great--thanks.  Your package is very useful and beautifully coded!
