### ISSUE TITLE
How to set custom background with transparency?

### ISSUE THREAD

**Issue by megamonster21099** [rubensousa/BottomSheetBuilder#20]
When i call setItemBackground(someDrawable) - this drawable is set over default white rectangle, but not replacing it. For example you can not set the background with rounded top corners. How can i reach this?

**Comment by rubensousa** [comment]
There's no way to do this, since the item background is drawn on top of the bottom sheet background. The item background setter is meant to change the background color or ripple, not to add custom borders or shapes.
