### ISSUE TITLE
How to make view bottomSheet dismissable with on touch outside?

### ISSUE THREAD

**Issue by pedrofsn** [rubensousa/BottomSheetBuilder#22]

**Comment by rubensousa** [comment]
It should already dismiss when you click outside. This is the default behavior on bottom sheet dialogs

**Comment by pedrofsn** [comment]
I show and hide using this method above:

```
private void controlarVisibilidadeSeletorImagem(boolean visivel) {
        mBehavior.setState(visivel ? BottomSheetBehavior.STATE_EXPANDED : BottomSheetBehavior.STATE_COLLAPSED);
    }
```

When bottom sheet is opened, it doesn't hide itself clicking outside.

**Comment by rubensousa** [comment]
Are you using a view or a BottomSheetDialog? Only BottomSheetDialogs hide themselves when you click outside.

**Comment by pedrofsn** [comment]
I'm using BottomSheetDialogFragment

**Comment by rubensousa** [comment]
There's no BottomSheetDialogFragment in this library. How are you creating the BottomSheet? This library uses a BottomSheetDialog.

**Comment by SammyO** [comment]
I can confirm that when using a view (instead of a BottomSheetDialog), clicking outside the dialog doesn't dismiss it.

**Comment by rubensousa** [comment]
That's intended behavior. I'm closing this since it's the developer's responsibility to handle touch events in that case.
