### ISSUE TITLE
Option to set ItemTintColor

### ISSUE THREAD

**Issue by defaultbr** [rubensousa/BottomSheetBuilder#3]
Hi Rubens, is there any way to add a options to .setItemColorTint or something like this? so i can avoid having more duplicate drawable for specific themes, i just need to set the tintColor

**Comment by rubensousa** [comment]
Hi, this will be added in 1.3
Commit: https://github.com/rubensousa/BottomSheetBuilder/commit/ec8f5f15087a9e90d883f894cdcc3ec973b2029d
