### ISSUE TITLE
The bottomsheet grid dialog does not expand on start in API 24 devices

### ISSUE THREAD

**Issue by swetakadam** [rubensousa/BottomSheetBuilder#7]
Hi,

I loved your work .. so I tried to integrate your work in our app .. However I tested it on API 24 and it does not expand on start ... I have          
                .expandOnStart(true) in the code

Here is the GIF 
![bottomsheet-api-24-issue](https://cloud.githubusercontent.com/assets/5216040/19786249/d3881d56-9c51-11e6-813d-e946281eaab3.gif)

**Comment by swetakadam** [comment]
it works fine on API 22, 23 and so on

**Comment by swetakadam** [comment]
@rubensousa - Please check this https://code.google.com/p/android/issues/detail?id=202396

**Comment by rubensousa** [comment]
Will be out in 1.4. Thanks!

**Comment by swetakadam** [comment]
@rubensousa  Thank you so much for your quick response

**Comment by rubensousa** [comment]
No problem. 1.4 is out now :)
```groovy
compile 'com.github.rubensousa:bottomsheetbuilder:1.4'
```
