### ISSUE TITLE
Add colors using attribute resId

### ISSUE THREAD

**Issue by codesForLiving** [rubensousa/BottomSheetBuilder#9]
Currently the background, title, etc colors can be set by color resId only. 

Using Attribute resId, would be more useful for theming purposes. 

Or, option to provide resolved  color values, would also do.

**Comment by rubensousa** [comment]
I'll try to work on this next week.

**Comment by codesForLiving** [comment]
@rubensousa Hello,
Did you get time to look into it?

**Comment by rubensousa** [comment]
I still didn't have time to work on this. I'll try later tonight though

**Comment by rubensousa** [comment]
Released in 1.5. Thanks for the suggestion :)
